/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.openslx.bwlp.thrift.iface;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DateParamError implements org.apache.thrift.TEnum {
  TOO_LOW(0),
  TOO_HIGH(1),
  NEGATIVE_RANGE(2);

  private final int value;

  private DateParamError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DateParamError findByValue(int value) { 
    switch (value) {
      case 0:
        return TOO_LOW;
      case 1:
        return TOO_HIGH;
      case 2:
        return NEGATIVE_RANGE;
      default:
        return null;
    }
  }
}
