/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.openslx.bwlp.thrift.iface;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SscMode implements org.apache.thrift.TEnum {
  OFF(0),
  ON(1),
  AUTO(2),
  USER(3);

  private final int value;

  private SscMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SscMode findByValue(int value) { 
    switch (value) {
      case 0:
        return OFF;
      case 1:
        return ON;
      case 2:
        return AUTO;
      case 3:
        return USER;
      default:
        return null;
    }
  }
}
