/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.openslx.bwlp.thrift.iface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-04")
public class TransferStatus implements org.apache.thrift.TBase<TransferStatus, TransferStatus._Fields>, java.io.Serializable, Cloneable, Comparable<TransferStatus> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TransferStatus");

  private static final org.apache.thrift.protocol.TField BLOCK_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("blockStatus", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("state", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TransferStatusStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TransferStatusTupleSchemeFactory());
  }

  public ByteBuffer blockStatus; // required
  /**
   * 
   * @see TransferState
   */
  public TransferState state; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BLOCK_STATUS((short)1, "blockStatus"),
    /**
     * 
     * @see TransferState
     */
    STATE((short)2, "state");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BLOCK_STATUS
          return BLOCK_STATUS;
        case 2: // STATE
          return STATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BLOCK_STATUS, new org.apache.thrift.meta_data.FieldMetaData("blockStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.STATE, new org.apache.thrift.meta_data.FieldMetaData("state", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TransferState.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TransferStatus.class, metaDataMap);
  }

  public TransferStatus() {
  }

  public TransferStatus(
    ByteBuffer blockStatus,
    TransferState state)
  {
    this();
    this.blockStatus = org.apache.thrift.TBaseHelper.copyBinary(blockStatus);
    this.state = state;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TransferStatus(TransferStatus other) {
    if (other.isSetBlockStatus()) {
      this.blockStatus = org.apache.thrift.TBaseHelper.copyBinary(other.blockStatus);
    }
    if (other.isSetState()) {
      this.state = other.state;
    }
  }

  public TransferStatus deepCopy() {
    return new TransferStatus(this);
  }

  @Override
  public void clear() {
    this.blockStatus = null;
    this.state = null;
  }

  public byte[] getBlockStatus() {
    setBlockStatus(org.apache.thrift.TBaseHelper.rightSize(blockStatus));
    return blockStatus == null ? null : blockStatus.array();
  }

  public ByteBuffer bufferForBlockStatus() {
    return org.apache.thrift.TBaseHelper.copyBinary(blockStatus);
  }

  public TransferStatus setBlockStatus(byte[] blockStatus) {
    this.blockStatus = blockStatus == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(blockStatus, blockStatus.length));
    return this;
  }

  public TransferStatus setBlockStatus(ByteBuffer blockStatus) {
    this.blockStatus = org.apache.thrift.TBaseHelper.copyBinary(blockStatus);
    return this;
  }

  public void unsetBlockStatus() {
    this.blockStatus = null;
  }

  /** Returns true if field blockStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetBlockStatus() {
    return this.blockStatus != null;
  }

  public void setBlockStatusIsSet(boolean value) {
    if (!value) {
      this.blockStatus = null;
    }
  }

  /**
   * 
   * @see TransferState
   */
  public TransferState getState() {
    return this.state;
  }

  /**
   * 
   * @see TransferState
   */
  public TransferStatus setState(TransferState state) {
    this.state = state;
    return this;
  }

  public void unsetState() {
    this.state = null;
  }

  /** Returns true if field state is set (has been assigned a value) and false otherwise */
  public boolean isSetState() {
    return this.state != null;
  }

  public void setStateIsSet(boolean value) {
    if (!value) {
      this.state = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BLOCK_STATUS:
      if (value == null) {
        unsetBlockStatus();
      } else {
        setBlockStatus((ByteBuffer)value);
      }
      break;

    case STATE:
      if (value == null) {
        unsetState();
      } else {
        setState((TransferState)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BLOCK_STATUS:
      return getBlockStatus();

    case STATE:
      return getState();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BLOCK_STATUS:
      return isSetBlockStatus();
    case STATE:
      return isSetState();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TransferStatus)
      return this.equals((TransferStatus)that);
    return false;
  }

  public boolean equals(TransferStatus that) {
    if (that == null)
      return false;

    boolean this_present_blockStatus = true && this.isSetBlockStatus();
    boolean that_present_blockStatus = true && that.isSetBlockStatus();
    if (this_present_blockStatus || that_present_blockStatus) {
      if (!(this_present_blockStatus && that_present_blockStatus))
        return false;
      if (!this.blockStatus.equals(that.blockStatus))
        return false;
    }

    boolean this_present_state = true && this.isSetState();
    boolean that_present_state = true && that.isSetState();
    if (this_present_state || that_present_state) {
      if (!(this_present_state && that_present_state))
        return false;
      if (!this.state.equals(that.state))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_blockStatus = true && (isSetBlockStatus());
    list.add(present_blockStatus);
    if (present_blockStatus)
      list.add(blockStatus);

    boolean present_state = true && (isSetState());
    list.add(present_state);
    if (present_state)
      list.add(state.getValue());

    return list.hashCode();
  }

  @Override
  public int compareTo(TransferStatus other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBlockStatus()).compareTo(other.isSetBlockStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlockStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blockStatus, other.blockStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetState()).compareTo(other.isSetState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.state, other.state);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TransferStatus(");
    boolean first = true;

    sb.append("blockStatus:");
    if (this.blockStatus == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.blockStatus, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("state:");
    if (this.state == null) {
      sb.append("null");
    } else {
      sb.append(this.state);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TransferStatusStandardSchemeFactory implements SchemeFactory {
    public TransferStatusStandardScheme getScheme() {
      return new TransferStatusStandardScheme();
    }
  }

  private static class TransferStatusStandardScheme extends StandardScheme<TransferStatus> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TransferStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BLOCK_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.blockStatus = iprot.readBinary();
              struct.setBlockStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.state = org.openslx.bwlp.thrift.iface.TransferState.findByValue(iprot.readI32());
              struct.setStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TransferStatus struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.blockStatus != null) {
        oprot.writeFieldBegin(BLOCK_STATUS_FIELD_DESC);
        oprot.writeBinary(struct.blockStatus);
        oprot.writeFieldEnd();
      }
      if (struct.state != null) {
        oprot.writeFieldBegin(STATE_FIELD_DESC);
        oprot.writeI32(struct.state.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TransferStatusTupleSchemeFactory implements SchemeFactory {
    public TransferStatusTupleScheme getScheme() {
      return new TransferStatusTupleScheme();
    }
  }

  private static class TransferStatusTupleScheme extends TupleScheme<TransferStatus> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TransferStatus struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBlockStatus()) {
        optionals.set(0);
      }
      if (struct.isSetState()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBlockStatus()) {
        oprot.writeBinary(struct.blockStatus);
      }
      if (struct.isSetState()) {
        oprot.writeI32(struct.state.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TransferStatus struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.blockStatus = iprot.readBinary();
        struct.setBlockStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.state = org.openslx.bwlp.thrift.iface.TransferState.findByValue(iprot.readI32());
        struct.setStateIsSet(true);
      }
    }
  }

}

