/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.openslx.bwlp.thrift.iface;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2021-12-17")
public enum TransferState implements org.apache.thrift.TEnum {
  IDLE(0),
  WORKING(1),
  FINISHED(2),
  ERROR(3);

  private final int value;

  private TransferState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TransferState findByValue(int value) { 
    switch (value) {
      case 0:
        return IDLE;
      case 1:
        return WORKING;
      case 2:
        return FINISHED;
      case 3:
        return ERROR;
      default:
        return null;
    }
  }
}
