/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.openslx.bwlp.thrift.iface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Virtualizer implements org.apache.thrift.TBase<Virtualizer, Virtualizer._Fields>, java.io.Serializable, Cloneable, Comparable<Virtualizer> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Virtualizer");

  private static final org.apache.thrift.protocol.TField VIRT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("virtId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField VIRT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("virtName", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new VirtualizerStandardSchemeFactory());
    schemes.put(TupleScheme.class, new VirtualizerTupleSchemeFactory());
  }

  public String virtId; // required
  public String virtName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VIRT_ID((short)1, "virtId"),
    VIRT_NAME((short)2, "virtName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VIRT_ID
          return VIRT_ID;
        case 2: // VIRT_NAME
          return VIRT_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VIRT_ID, new org.apache.thrift.meta_data.FieldMetaData("virtId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VIRT_NAME, new org.apache.thrift.meta_data.FieldMetaData("virtName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Virtualizer.class, metaDataMap);
  }

  public Virtualizer() {
  }

  public Virtualizer(
    String virtId,
    String virtName)
  {
    this();
    this.virtId = virtId;
    this.virtName = virtName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Virtualizer(Virtualizer other) {
    if (other.isSetVirtId()) {
      this.virtId = other.virtId;
    }
    if (other.isSetVirtName()) {
      this.virtName = other.virtName;
    }
  }

  public Virtualizer deepCopy() {
    return new Virtualizer(this);
  }

  @Override
  public void clear() {
    this.virtId = null;
    this.virtName = null;
  }

  public String getVirtId() {
    return this.virtId;
  }

  public Virtualizer setVirtId(String virtId) {
    this.virtId = virtId;
    return this;
  }

  public void unsetVirtId() {
    this.virtId = null;
  }

  /** Returns true if field virtId is set (has been assigned a value) and false otherwise */
  public boolean isSetVirtId() {
    return this.virtId != null;
  }

  public void setVirtIdIsSet(boolean value) {
    if (!value) {
      this.virtId = null;
    }
  }

  public String getVirtName() {
    return this.virtName;
  }

  public Virtualizer setVirtName(String virtName) {
    this.virtName = virtName;
    return this;
  }

  public void unsetVirtName() {
    this.virtName = null;
  }

  /** Returns true if field virtName is set (has been assigned a value) and false otherwise */
  public boolean isSetVirtName() {
    return this.virtName != null;
  }

  public void setVirtNameIsSet(boolean value) {
    if (!value) {
      this.virtName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VIRT_ID:
      if (value == null) {
        unsetVirtId();
      } else {
        setVirtId((String)value);
      }
      break;

    case VIRT_NAME:
      if (value == null) {
        unsetVirtName();
      } else {
        setVirtName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VIRT_ID:
      return getVirtId();

    case VIRT_NAME:
      return getVirtName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VIRT_ID:
      return isSetVirtId();
    case VIRT_NAME:
      return isSetVirtName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Virtualizer)
      return this.equals((Virtualizer)that);
    return false;
  }

  public boolean equals(Virtualizer that) {
    if (that == null)
      return false;

    boolean this_present_virtId = true && this.isSetVirtId();
    boolean that_present_virtId = true && that.isSetVirtId();
    if (this_present_virtId || that_present_virtId) {
      if (!(this_present_virtId && that_present_virtId))
        return false;
      if (!this.virtId.equals(that.virtId))
        return false;
    }

    boolean this_present_virtName = true && this.isSetVirtName();
    boolean that_present_virtName = true && that.isSetVirtName();
    if (this_present_virtName || that_present_virtName) {
      if (!(this_present_virtName && that_present_virtName))
        return false;
      if (!this.virtName.equals(that.virtName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Virtualizer other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVirtId()).compareTo(other.isSetVirtId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVirtId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.virtId, other.virtId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVirtName()).compareTo(other.isSetVirtName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVirtName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.virtName, other.virtName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Virtualizer(");
    boolean first = true;

    sb.append("virtId:");
    if (this.virtId == null) {
      sb.append("null");
    } else {
      sb.append(this.virtId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("virtName:");
    if (this.virtName == null) {
      sb.append("null");
    } else {
      sb.append(this.virtName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VirtualizerStandardSchemeFactory implements SchemeFactory {
    public VirtualizerStandardScheme getScheme() {
      return new VirtualizerStandardScheme();
    }
  }

  private static class VirtualizerStandardScheme extends StandardScheme<Virtualizer> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Virtualizer struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VIRT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.virtId = iprot.readString();
              struct.setVirtIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VIRT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.virtName = iprot.readString();
              struct.setVirtNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Virtualizer struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.virtId != null) {
        oprot.writeFieldBegin(VIRT_ID_FIELD_DESC);
        oprot.writeString(struct.virtId);
        oprot.writeFieldEnd();
      }
      if (struct.virtName != null) {
        oprot.writeFieldBegin(VIRT_NAME_FIELD_DESC);
        oprot.writeString(struct.virtName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VirtualizerTupleSchemeFactory implements SchemeFactory {
    public VirtualizerTupleScheme getScheme() {
      return new VirtualizerTupleScheme();
    }
  }

  private static class VirtualizerTupleScheme extends TupleScheme<Virtualizer> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Virtualizer struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVirtId()) {
        optionals.set(0);
      }
      if (struct.isSetVirtName()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetVirtId()) {
        oprot.writeString(struct.virtId);
      }
      if (struct.isSetVirtName()) {
        oprot.writeString(struct.virtName);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Virtualizer struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.virtId = iprot.readString();
        struct.setVirtIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.virtName = iprot.readString();
        struct.setVirtNameIsSet(true);
      }
    }
  }

}

